#pragma once

#define IOCTL_UNPLUG_USB_DEVICE CTL_CODE(FILE_DEVICE_CONTROLLER, 0x1000, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_PLUG_USB_DEVICE CTL_CODE(FILE_DEVICE_CONTROLLER, 0x1001, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GET_DRIVER_INFO CTL_CODE(FILE_DEVICE_CONTROLLER, 0x1002, METHOD_NEITHER, FILE_ANY_ACCESS)
